---

language: python

matrix:
  include:
    - os: linux
      dist: trusty
      python: "2.7"
    - os: osx
      language: generic

cache: pip

install:
  - pip install ansible
  - pip install ansible-lint

script:
  - make test
