---

- hosts: all
  tasks:
    - name: git
      apt: name=git state=present
      become: yes

    - name: .gitconfig
      file: src={{ playbook_dir }}/files/gitconfig dest=~/.gitconfig state=link force=true
      tags: git

    - name: .tmux.conf
      file: src={{ playbook_dir }}/files/tmux.conf dest=~/.tmux.conf state=link force=true
      tags: tmux

    - name: gemrc
      file: src={{ playbook_dir }}/files/gemrc dest=~/.gemrc state=link force=true
      tags: ruby

    - name: inputrc
      file: src={{ playbook_dir }}/files/inputrc dest=~/.inputrc state=link force=true
      tags: bash

    - name: vim config
      file: src={{ playbook_dir }}/files/vimrc dest=~/.vimrc state=link force=true
      tags: vim

    - name: vim plugin manager
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
        version: master
        update: no
      tags: vim

    - name: .lein dir
      file: path=~/.lein state=directory
      tags: [clojure, lein]

    - name: lein profiles
      file: src={{ playbook_dir }}/files/profiles.clj dest=~/.lein/profiles.clj state=link force=yes
      tags: [clojure, lein]

    - name: bash ps1
      lineinfile: dest="~/.bash_profile" state=present create=yes
        line="export PS1='`if [ $? = 0 ]; then echo \"\[\033[01;32m\]✔\"; else echo \"\[\033[01;31m\]✘\"; fi` \[\033[01;32m\]\h\[\033[35m\]$(__git_ps1 \" %s\")\[\033[01;34m\] \W \[\033[01;30m\]>\[\033[00m\] '"
      tags: bash
