---

- hosts: all
  gather_facts: no
  tasks:
    - name: git
      apt: name=git state=present
      become: yes
      tags: git

    - include: playbooks/ubuntu.yml
      become: yes
      tags: ubuntu

    - include: playbooks/nvim.yml
      tags: nvim

    - include: playbooks/dotfiles.yml
      tags: dotfiles

    - include: playbooks/gem.yml
      become: yes
      tags: ruby

    - include: playbooks/pip.yml
      become: yes
      tags: python, pip
