---

- hosts: all
  tasks:
    - name: vim
      import_tasks: playbooks/vim.yml
      tags: vim

    - name: dotfiles
      import_tasks: playbooks/dotfiles.yml
      tags: dotfiles

    - name: iterm2
      import_tasks: playbooks/iterm2.yml
      tags: [iterm]
      when: ansible_distribution == 'MacOSX'
