---

- hosts: all

  tasks:
    - name: Install basic tools
      apt: name={{ item }} state=latest #update_cache=yes
      with_items:
        - curl
        - git
        - vim
        - wget
      become: yes

    - file: src={{ playbook_dir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - gitconfig
        - vimrc 

    # Vim. Vundle plugin manager
    - git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
        version: v0.10.2

    # Python
    - name: Install Python pip
      easy_install: name=pip
      become: yes
      tags: python

    - name: Upgrade pip
      pip: name=pip extra_args='--upgrade'

    - name: Install Python modules with pip
      pip: name={{ item }} state=latest
      with_items:
        - certifi
        - pyopenssl
        - ndg-httpsclient
        - pyasn1
        - pylint
        - ansible-lint
      become: yes
      tags: python
