---

- hosts: all
  gather_facts: no
  tasks:
    - name: git
      apt: name=git state=present
      become: yes
      tags: git

    - include: playbooks/ubuntu.yml
      become: yes
      tags: ubuntu

    - include: playbooks/nvim.yml
      tags: nvim

    - include: playbooks/dotfiles.yml
      tags: dotfiles
