---

- hosts: all

  tasks:
    - name: Install basic tools
      apt: name={{ item }} state=latest
      become: yes
      with_items:
        - curl
        - exuberant-ctags
        - git
        - vim
        - wget

    - name: Set dotfiles (.vimrc, .gitconfig, etc)
      file: src={{ playbook_dir }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - gitconfig
        - vimrc
      tags: vim

    - name: Vim Vundle plugin manager
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
        version: master
      tags: vim

    - name: Install build-essential
      apt: name={{ item }} state=latest
      become: yes
      with_items:
        - build-essential
        - libssl-dev
        - libffi-dev
        - python-dev

    - name: Install Python pip
      easy_install: name=pip
      become: yes
      tags: python

    - name: Upgrade pip
      pip: name=pip extra_args='--upgrade'
      become: yes
      tags: python

    - name: Install Python modules with pip
      pip: name={{ item }} state=latest
      become: yes
      with_items:
        - certifi
        - pyopenssl
        - ndg-httpsclient
        - pyasn1
        - pylint
        - ansible-lint
      tags: python

    - name: Check nvm
      stat: path=~/.nvm
      register: nvm_path
      tags: node

    - name: Check node version
      when: nvm_path.stat.exists
      command: node -v
      register: node_version
      ignore_errors: yes
      tags: node

    - name: Check npm
      when: nvm_path.stat.exists and node_version | success
      stat: path=~/.nvm/versions/{{ node_version.stdout }}/bin/npm
      register: npm_path
      tags: node

    - name: Install npm packages
      when: nvm_path.stat.exists and node_version | success and npm_path.stat.exists
      npm: name={{ item }} global=yes state=latest
        executable=~/.nvm/versions/{{ node_version.stdout }}/bin/npm
      with_items:
        - bower
        - js-yaml
        - eslint
        - babel-eslint
        - eslint-plugin-react
        - jsonlint
      tags: node
