---

- hosts: all
  gather_facts: no
  tasks:
    - name: git
      apt: name=git state=present
      become: yes
      tags: git

    - include: playbooks/vim.yml
      tags: dotfiles, vim

    - include: playbooks/dotfiles.yml
      tags: dotfiles

    - include: playbooks/ubuntu.yml
      become: yes
      tags: ubuntu

    - include: playbooks/pip.yml
      become: yes
      tags: python, pip
