---

- hosts: all
  tasks:
    - name: git
      apt: name=git state=present
      become: yes
      tags: git

    - include: playbooks/ubuntu.yml
      become: yes
      tags: ubuntu

    - include: playbooks/vim.yml
      tags: vim

    - include: playbooks/dotfiles.yml
      tags: dotfiles

    - include: playbooks/iterm.yml
      tags: [iterm]
      when: ansible_distribution == 'MacOSX'
