- block:
  - name: iTerm2 | Specify the preferences directory
    osx_defaults:
      domain: com.googlecode.iterm2.plist
      key: PrefsCustomFolder
      type: string
      value: "{{ playbook_dir }}/files/iterm2/"
      state: present
  - name: iTerm2 | Tell iTerm2 to use the custom preferences in the directory
    osx_defaults:
      domain: com.googlecode.iterm2.plist
      key: LoadPrefsFromCustomFolder
      type: bool
      value: true
      state: present
