- block:
  - name: add NeoVim ppa
    apt_repository: repo='ppa:neovim-ppa/unstable' state=present

  - name: install nvim
    apt: name=neovim state=present

  - name: install nvim python-client
    pip: name=neovim state=present

  become: true
  when: ansible_os_family == "Debian"

- name: prepare config directory
  file: path={{ item }}/autoload state=directory recurse=Yes
  with_items:
    - ~/.vim/
    - ~/.config/nvim
  tags: [dotfiles, vim]

- name: install vim-plug
  get_url:
    dest: "{{ item }}/autoload/plug.vim"
    url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  with_items:
    - ~/.vim/
    - ~/.config/nvim/
  tags: [dotfiles, vim]

- name: nvim config
  file: src={{ playbook_dir }}/files/vimrc dest=~/.config/nvim/init.vim state=link force=true
  tags: [dotfiles, vim]

- name: vim config
  file: src={{ playbook_dir }}/files/vimrc dest=~/.vimrc state=link force=true
  tags: [dotfiles, vim]
